version: '2'
services:
    app:
        container_name: app
        restart: always
        build: .
        ports:
            - '8139:8139'
        links:
            - mongo
    mongo:
        container_name: mongo1
        image: mongo
        ports:
            - '27017:27017'
